// Auto-generated theme configuration from *.ui_skins.themes.yml files
// This file is automatically generated - do not edit manually

// Theme target mapping
const themeTargets = {
    'cyberpunk': 'body',
    'forest': 'html',
    'garden': 'html'
};

// Add a decorator to set data-theme on the correct target element
export const themeDecorators = [
  (storyFn, context) => {
    // Wait for the target element to be available
    setTimeout(() => {
      const selectedTheme = context.globals.theme || 'cyberpunk';
      const targetSelector = themeTargets[selectedTheme] || 'body';
      
      // Remove data-theme from both html and body to clean previous themes
      const html = document.querySelector('html');
      const body = document.querySelector('body');
      if (html) html.removeAttribute('data-theme');
      if (body) body.removeAttribute('data-theme');
      
      // Apply the new theme to the correct target
      const target = document.querySelector(targetSelector);
      if (target) {
        target.setAttribute('data-theme', selectedTheme);
      }
    }, 0);
    return storyFn();
  },
];

export const themeGlobalTypes = {
  theme: {
    name: 'Theme',
    description: 'Global theme for components',
    defaultValue: 'cyberpunk',
    toolbar: {
      icon: 'paintbrush',
      items: [
        { value: 'cyberpunk', title: 'Cyberpunk' },
        { value: 'forest', title: 'Forest' },
        { value: 'garden', title: 'Garden' }
      ],
    },
  },
};
